### ISSUE TITLE
Error: Cannot find module 'babel-runtime/regenerator'

### ISSUE THREAD

**Issue by lzrski** [ulisses-alves/rollup-plugin-elm#1]
Hello and thanks for your work on this plugin.

I got it to work and so far it seems to do it's job, but at first after installing it I got following error:

```
[!] Error: Cannot find module 'babel-runtime/regenerator'
Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/.../node_modules/rollup-plugin-elm/dist/rollup-plugin-elm.cjs.js:1:516)
    at Module._compile (module.js:612:30)
    at Module._extensions..js (module.js:623:10)
    at Object.require.extensions..js (/.../node_modules/rollup/bin/rollup:2777:17)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
```

Adding `babel-runtime` to my project fixed the problem:

```sh
npm install --save-dev babel-runtime
```

It's not clear to me why this `babel-runtime/regenerator` is even needed, but perhaps it should be a dependency of this project.

Anyway thanks and keep up your good work :-)

**Comment by ulisses-alves** [comment]
Hey @lzrski,

I will check it out at some point today. I might just get rid of the "await" statement in the code so runtime is no longer a dependency.

Thanks for the feedback though.

**Comment by ulisses-alves** [comment]
I have completely removed the src dependency on Babel, so this should be fixed now.
